services:
  studyzone-angular:
    image: llm/studyzone-angular:latest
    container_name: studyzone-angular
    build:
      context: ../../
      dockerfile: angular/Dockerfile.local
    ports:
      - "4200:80"
    depends_on:
      - studyzone-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network

  studyzone-api:
    image: llm/studyzone-api:latest
    container_name: studyzone-api
    hostname: studyzone-api
    build:
      context: ../../
      dockerfile: src/LLM.StudyZone.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=3785646d-789b-43b4-8512-c9d661fde730
      - App__SelfUrl=https://localhost:44332
      - App__AngularUrl=http://localhost:4200
      - App_CorsOrigins=http://localhost:4200
      - App__HealthCheckUrl=http://studyzone-api:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://studyzone-authserver:8080
      - AuthServer__MetaAddress=https://localhost:44386
      - App__MVCPublicUrl=https://localhost:44312
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=StudyZone;Pooling=false;
      - Redis__Configuration=redis
    ports:
      - "44357:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure    
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network
  
  studyzone-authserver:
    image: llm/studyzone-authserver:latest
    container_name: studyzone-authserver
    build:
      context: ../../
      dockerfile: src/LLM.StudyZone.AuthServer/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - App__SelfUrl=https://localhost:44386
      - App__CorsOrigins=http://localhost:4200,https://localhost:44357
      - App__HealthCheckUrl=http://studyzone-authserver:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44386
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=3785646d-789b-43b4-8512-c9d661fde730
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=StudyZone;Pooling=false;
      - Redis__Configuration=redis
    ports:
      - "44386:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network

  studyzone-web-public:
    image: llm/studyzone-web-public:latest
    container_name: studyzone-web-public
    build:
      context: ../../
      dockerfile: src/LLM.StudyZone.Web.Public/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=3785646d-789b-43b4-8512-c9d661fde730
      - App__SelfUrl=https://localhost:44312
      - App__HealthCheckUrl=http://studyzone-web-public:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__IsOnK8s=true      
      - RemoteServices__Default__BaseUrl=http://studyzone-api:8080
      - AuthServer__Authority=https://localhost:44386/    
      - AuthServer__MetaAddress=http://studyzone-authserver:8080
      - RemoteServices__AbpAccountPublic__BaseUrl=http://studyzone-authserver:8080
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=StudyZone;Pooling=false;
      - Redis__Configuration=redis
    ports:
      - "44312:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network  
  db-migrator:
    image: llm/studyzone-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/LLM.StudyZone.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__StudyZone_App__RootUrl=http://localhost:4200
      - OpenIddict__Applications__StudyZone_Swagger__RootUrl=https://localhost:44357
      - OpenIddict__Applications__StudyZone_Web_Public__RootUrl=https://localhost:44312
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=StudyZone;Pooling=false;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - abp-network    
  
  postgres:
    container_name: postgres-db
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "myPassw0rd"
    volumes:
      - postgres_data:/var/opt/postgres
    networks: 
      - abp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5    
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network  
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      
volumes:
  postgres_data:
    name: studyzone_postgres_data
networks:
  abp-network:
    name: studyzone-network
    driver: bridge
